OpenMined/syft

notebooks/analytics.ipynb
syftbox/server/analytics.py

fix glob pattern for analytics logs

---

syftbox/client/plugins/apps.py
syftbox/client/routers/app_router.py

- App Log Location: `~/Syftbox/apis/<app_name>/logs/<app_name>.log`
- App location is displayed in syftbox client logs. If there is some error in app execution, its highlighted in the client logs.
Client Logs:
closes #369 

Separate log file for running Apps

---

syftbox/app/install.py

Having issue installing app via symbolic link with the new `apps --> apis` change. I think this is the fix but looking for a review from someone with context.

minor fix apps --> apis change

---

syftbox/client/auth.py
syftbox/server/settings.py
syftbox/server/users/auth.py
syftbox/server/users/router.py
tests/unit/server/conftest.py

auth: remove b64, check if email and email_token match

---

syftbox/app/install.py
syftbox/client/client2.py
syftbox/client/routers/index_router.py
syftbox/client/utils/error_reporting.py
syftbox/lib/client_config.py

Temporary fix for client config serde in error report

---

MANIFEST.in

Add png to MANIFEST.in

---

syftbox/lib/email.py

change email

---

syftbox/server/emails/models.py
syftbox/server/emails/router.py

Remove batch email API to prevent abuse and YAGNI

---

.github/workflows/e2e-tests.yaml

Revert "Fix running out of space for e2e model training test"

---

.github/workflows/e2e-tests.yaml
tests/e2e/test_fl_model_aggregator.py
tests/e2e/test_fl_model_training.py

Test FL based model training tutorial flow.

add e2e test for fl model training

---

syftbox/lib/constants.py
syftbox/lib/email.py
syftbox/server/emails/constants.py
syftbox/server/emails/models.py
syftbox/server/emails/router.py
syftbox/server/settings.py

Update auth email sender and change notifications email to SendGrid

---

syftbox/client/cli_setup.py

Closes OpenMined/syft-internal-issues#221

Preserve the `<WorkSpace>/apis/` folder between syft versions

---

.github/workflows/e2e-tests.yaml
tests/e2e/test_aggregator_with_local_training.py
tests/e2e/test_fl_model_training.py

Closes https://github.com/OpenMined/syft-internal-issues/issues/227

Fix flaky e2e test

---

syftbox/assets/templates/sync_dashboard.jinja2
syftbox/client/plugins/sync/consumer.py
syftbox/client/plugins/sync/local_state.py
syftbox/server/sync/hash.py
tests/unit/hash_test.py

revert localstate path

---

tests/e2e/test_fl_model_training.py

change model arch filename

---

syftbox/client/plugins/apps.py

closes https://github.com/OpenMined/syft-internal-issues/issues/5

fix client shutdown

---

.github/workflows/e2e-tests.yaml

Since the tests for fl are flaking , currently temporarily disabling e2e

[ci] temporarily disable fl model training

---

default_apps/starter_app/main.py

ADD cpu_tracker as a default app

---

pyproject.toml

Test Renovate

---

.pre-commit-config.yaml
renovate.json

update renovate schema

---

syftbox/lib/permissions.py
syftbox/server/db/db.py
syftbox/server/server.py

fix staging issues

---

syftbox/client/base.py
syftbox/client/client2.py
syftbox/lib/datasite.py
syftbox/lib/lib.py
syftbox/lib/permissions.py
tests/integration/sync/conftest.py
tests/integration/sync/sync_reject_test.py
tests/integration/sync/sync_test.py

Fix perm factory methods

---

syftbox/server/middleware.py
syftbox/server/server.py
syftbox/server/settings.py
tests/unit/server/sync_endpoint_test.py

The PR adds a server side Request Size Limit, to discard requests greater than 10 MB
Add tests for the same

Server Request Size Limit

---

syftbox/lib/http.py
syftbox/server/server.py
syftbox/server/telemetry.py

track user geo location of the client user

---

pyproject.toml
syftbox/tui/cli.py
uv.lock

staging fix

---

justfile

uncomment justfile

---

.github/workflows/cd-release.yaml

fix cd release

---

syftbox/client/cli_setup.py
syftbox/client/server_client.py
syftbox/client/utils/error_reporting.py
syftbox/lib/http.py
syftbox/lib/version_utils.py
syftbox/server/middleware.py
syftbox/server/server.py

cleanup otel

---

syftbox/client/base.py
syftbox/lib/version_utils.py
syftbox/server/middleware.py

Fix version and timeout

---

syftbox/server/server.py

fix http_capture_headers_server_request

---

syftbox/server/api/v1/main_router.py

Fix template paths

---

syftbox/tui/cli.py

closes https://github.com/OpenMined/syft-internal-issues/issues/289

add TUI warning

---

syftbox/server/api/v1/main_router.py

Add support for serving more file types in main router

---

syftbox/lib/permissions.py

add get_computed_permission

---

.github/workflows/apps-tests.yaml

apps test exit code fix
